# Generated by Django 5.0.4 on 2024-08-01 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_bookcomment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name_plural': 'ผู้เเต่ง'},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-create'], 'verbose_name_plural': 'หนังสือ'},
        ),
        migrations.AlterModelOptions(
            name='bookcomment',
            options={'ordering': ['id'], 'verbose_name_plural': 'BookComment'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'หมวดหมู่'},
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
