# Generated by Django 4.2.3 on 2024-08-12 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_alter_author_options_alter_book_options_and_more'),
        ('book', '0006_book_image'),
    ]

    operations = [
    ]
