# Generated by Django 4.2.3 on 2025-03-20 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_merge_20240812_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.CharField(blank=True, choices=[('A', 'On Design'), ('B', 'Inplementation'), ('C', 'Evalation'), ('D', 'On ECN Phase'), ('E', 'Relaesed')], max_length=10, null=True),
        ),
    ]
