# Generated by Django 4.2.3 on 2025-03-20 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_book_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='status',
        ),
        migrations.AddField(
            model_name='book',
            name='image2',
            field=models.FileField(blank=True, null=True, upload_to='upload'),
        ),
        migrations.AlterField(
            model_name='book',
            name='level',
            field=models.CharField(blank=True, choices=[('Evaluation', 'Evaluation'), ('Design', 'Design'), ('Implementation', 'Implementation'), ('ECN under review', 'ECN under review')], max_length=20, null=True),
        ),
    ]
